"""Repo-level operations that span bundles: the common catalog and cross-bundle search.

Each bundle stays individually OKF-conformant; these views live OUTSIDE every
bundle (catalog.md at the repo root) and are synthesized by scanning
frontmatter, as spec S3.1/S8 anticipate consumers doing.
"""

from __future__ import annotations

from pathlib import Path

from . import okf
from .config import Config

CATALOG_NAME = "catalog.md"


def concepts(cfg: Config, bundle: str | None = None):
    """Yield (bundle_name, path, meta, body) for every concept in the repo."""
    for name, root in cfg.bundle_roots():
        if bundle and name != bundle:
            continue
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*.md")):
            if path.name in okf.RESERVED:
                continue
            try:
                meta, body = okf.parse(path)
            except Exception:
                meta, body = {}, ""
            yield name, path, meta, body


def rebuild_catalog(cfg: Config) -> Path:
    """Write catalog.md at the repo root: every bundle, every concept, one page."""
    lines = [
        "# Knowledge Catalog",
        "",
        "Common index across all OKF bundles in this repo. Generated by",
        "`llmwiki reindex`; do not edit by hand. Bundles are defined in",
        "[config.yaml](config.yaml).",
    ]
    total = 0
    for name, root in cfg.bundle_roots():
        info = cfg.bundles.get(name, {})
        lines += ["", f"## {name} — {info.get('title', name)}", ""]
        if info.get("description"):
            lines += [info["description"], ""]
        entries = list(concepts(cfg, bundle=name))
        total += len(entries)
        if not entries:
            lines.append("*(empty)*")
        for _, path, meta, _ in entries:
            rel = path.relative_to(cfg.repo_root)
            title = meta.get("title") or path.stem
            desc = str(meta.get("description") or "").strip()
            status = f", {meta['status']}" if meta.get("status") not in (None, "stable") else ""
            lines.append(
                f"* [{title}]({rel}) ({meta.get('type', 'Concept')}{status})"
                + (f" - {desc}" if desc else "")
            )
    lines[2:2] = [f"{len(cfg.bundles)} bundles, {total} concepts.", ""]
    path = cfg.repo_root / CATALOG_NAME
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def search(cfg: Config, query: str, limit: int = 20, bundle: str | None = None) -> list[dict]:
    """Rank concepts across bundles against query terms (frontmatter-weighted)."""
    terms = [t for t in query.lower().split() if t]
    results = []
    for name, path, meta, body in concepts(cfg, bundle=bundle):
        title = str(meta.get("title") or path.stem).lower()
        tags = " ".join(map(str, meta.get("tags") or [])).lower()
        desc = str(meta.get("description") or "").lower()
        body_l = body.lower()
        score = 0
        for t in terms:
            score += 4 * (t in title) + 3 * (t in tags) + 2 * (t in desc)
            score += min(body_l.count(t), 5)
        if score == 0:
            continue
        snippet = next(
            (ln.strip() for ln in body.splitlines() if ln.strip() and any(t in ln.lower() for t in terms)),
            "",
        )
        results.append(
            {
                "bundle": name,
                "path": str(path.relative_to(cfg.repo_root)),
                "type": meta.get("type", "Concept"),
                "title": meta.get("title") or path.stem,
                "description": meta.get("description") or "",
                "status": meta.get("status", "stable"),
                "score": score,
                "snippet": snippet[:200],
            }
        )
    results.sort(key=lambda r: -r["score"])
    return results[:limit]
